name: CI/CD Pipeline

on:
  push:
    branches: [ sesi30-devsecops ]
  pull_request:
    branches: [ sesi30-devsecops ]

jobs:
  unit_test:
    uses: ./.github/workflows/unit_test.yml

  sast:
    needs: unit_test
    uses: ./.github/workflows/sast.yml

  sca:
    needs: sast
    uses: ./.github/workflows/sca.yml

  secret_scan:
    needs: sca
    uses: ./.github/workflows/secret_scan.yml

  build_and_push:
    needs: secret_scan
    uses: ./.github/workflows/build_and_push.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  image_scan:
    needs: build_and_push
    uses: ./.github/workflows/image_scan.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
